Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: ${self:custom.Email}
          Protocol: "email"
      TopicName: ${self:custom.TopicName}

  Parameters:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: My EXP parameter
      Value: NA
      Name: ${self:custom.parameterName}
